# Generated by Django 4.1.2 on 2022-11-08 21:51

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='0-active category, 1-non active')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('initial_stock', models.IntegerField()),
                ('item_remain', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('item_description', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=order.models.get_file_path)),
                ('status', models.BooleanField(default=False, help_text='0-in stock, 1-out of stock')),
                ('ordered', models.BooleanField(default=False, help_text='0-not selected, 1-selected')),
                ('selected_itm', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='order.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False, help_text='0-free table, 1-occupied')),
                ('all_item_delivered', models.BooleanField(default=False, help_text=' 1-complete')),
                ('paid', models.BooleanField(default=False, help_text='0-not paid, 1-paid')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False, help_text='0-Processing, 1-Delivered')),
                ('order_note', models.CharField(blank=True, max_length=250, null=True)),
                ('ordered', models.BooleanField(default=False, help_text='0-Default, 1-order placed')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.items')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.tables')),
            ],
        ),
    ]
