# Generated by Django 4.1.2 on 2022-11-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_note', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False, help_text='0-Default, 1-paid')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.items')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.tables')),
            ],
        ),
    ]
